spring.application.name=busreservation

spring.datasource.url=jdbc:mysql://localhost:3306/busdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=21Ne1a05f4@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pgvsaikumar7890@gmail.com
spring.mail.password=kdhxyouoahwmpavj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cloudinary Configuration
cloudinary.cloud_name=dsdtgxusj
cloudinary.api_key=573875934215779
cloudinary.api_secret=wiaeHxNlL7I8e4u35dZAIQUnyhk
